### ISSUE TITLE
Rendering issues using dompdf

### ISSUE THREAD

**Issue by rafhun** [sprain/php-swiss-qr-bill#122]
Background info: Woocommerce shop with the Woocommerce Invoices Plugin that generates invoice PDFs using the dompdf library. Using their filter I am trying to append the QR bill HTML. This works fine (HTML output before dompdf looks correct)
 however in the generated PDF there are some layout issues.

- the invoice is wider than the page (offsetting the 2cm page margins defined by the general styles by applying negative margins does not fix this)
- the amount area in the payment part does not look as expected: amount is pushed down and currency does not float to its left

Screenshot for illustration.
![screenshot 2021-04-20 um 10 03 44](https://user-images.githubusercontent.com/7340779/115360682-2450cd00-a1c0-11eb-8f32-81c75dfb2b3d.png)

Check below styles to understand the meaning of border colors.

```css
#qr-bill {
    border: 1px solid red;
}

#qr-bill-amount-area {
    border: 1px solid red;
}

#qr-bill-currency {
    border: 1px solid blue;
}

#qr-bill-amount {
    border: 1px solid green;
}

#qr-bill-amount h2 {
    border: 1px solid black;
}

#qr-bill-amount p {
    border: 1px solid purple;
}

#qr-bill-currency h2 {
    border: 1px solid red;
}

#qr-bill-currency p {
    border: 1px solid teal;
}
```
